/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@EntityScan(basePackages = {"commons", "server"})
@EnableJpaRepositories(basePackages = {"oop_poliheh"})
public class App {


    public static void main(String[] args) {
        SpringApplication.run(App.class, args);    }
}


